<?php
return array (
  'enabled' => true,
  'default_model' => getenv('AIF_DEFAULT_MODEL') ?: 'mimo-v2.5-pro',
  'enable_upstream_fallback' => true,
  'fallback_for_explicit_model' => false,
  'simulate_stream' => true,
  'fallback_models' => 
  array (
    0 => 'mimo-v2.5-pro',
    1 => 'nvidia-qwen3-5-397b-a17b',
    2 => 'nvidia-qwen3-5-122b-a10b',
  ),
  'verify_ssl' => true,
  'user_agent' => 'MusicSite/1.0',
  'models' => 
  array (
    'mimo-v2.5-pro' => 
    array (
      'enabled' => true,
      'label' => 'Xiaomi MiMo v2.5 Pro',
      'type' => 'reasoning',
      'protocol' => 'openai_compatible',
      'provider' => 'mimo',
      'provider_key' => 'mimo',
      'base_url' => getenv('MIMO_API_BASE') ?: getenv('XIAOMI_MIMO_API_BASE') ?: getenv('MIMO_TOKEN_PLAN_API_BASE') ?: 'https://token-plan-cn.xiaomimimo.com/v1',
      'path' => '/chat/completions',
      'model_name' => 'mimo-v2.5-pro',
      'auth_type' => 'bearer',
      'api_key' => getenv('MIMO_API_KEY') ?: getenv('XIAOMI_MIMO_API_KEY') ?: getenv('MIMO_TOKEN_PLAN_API_KEY') ?: 'tp-ceggky3ffwto7kksam89rhpuc48lyateiu7avj9id4gjbbiq',
      'timeout' => 180,
      'temperature' => 0.7,
      'top_p' => 0.9,
      'presence_penalty' => 0,
      'frequency_penalty' => 0,
      'max_tokens' => 8192,
      'requires_quota' => true,
      'stream_supported' => true,
      'supports_thinking' => true,
      'drop_request_fields' => array('logprobs', 'top_logprobs'),
      'aliases' => 
      array (
        0 => 'mimov2.5pro',
        1 => 'mimo-v2.5pro',
        2 => 'MiMo-v2.5-pro',
        3 => 'mimo::mimov2.5pro',
        4 => 'xiaomi-mimo-v2.5-pro',
      ),
    ),

    'mimo-v2.5-pro-key2' => 
    array (
      'enabled' => true,
      'label' => 'Xiaomi MiMo v2.5 Pro · Key 2',
      'type' => 'reasoning',
      'protocol' => 'openai_compatible',
      'provider' => 'mimo2',
      'provider_key' => 'mimo2',
      'base_url' => getenv('MIMO2_API_BASE') ?: getenv('MIMO_V2_API_BASE') ?: getenv('XIAOMI_MIMO2_API_BASE') ?: getenv('XIAOMI_MIMO_V2_API_BASE') ?: getenv('MIMO_TOKEN_PLAN_2_API_BASE') ?: getenv('MIMO_API_BASE') ?: getenv('XIAOMI_MIMO_API_BASE') ?: getenv('MIMO_TOKEN_PLAN_API_BASE') ?: 'https://token-plan-cn.xiaomimimo.com/v1',
      'path' => '/chat/completions',
      'model_name' => 'mimo-v2.5-pro',
      'auth_type' => 'bearer',
      'api_key' => getenv('MIMO2_API_KEY') ?: getenv('MIMO_V2_API_KEY') ?: getenv('XIAOMI_MIMO2_API_KEY') ?: getenv('XIAOMI_MIMO_V2_API_KEY') ?: getenv('MIMO_TOKEN_PLAN_2_API_KEY') ?: 'tp-cwc4r892qy7e3elz4w6ycig4n07vw4qhl9t083eg40n3z5w4',
      'timeout' => 180,
      'temperature' => 0.7,
      'top_p' => 0.9,
      'presence_penalty' => 0,
      'frequency_penalty' => 0,
      'max_tokens' => 8192,
      'requires_quota' => true,
      'stream_supported' => true,
      'supports_thinking' => true,
      'drop_request_fields' => array('logprobs', 'top_logprobs'),
      'aliases' => 
      array (
        0 => 'mimov2.5pro-key2',
        1 => 'mimo-v2.5-pro-key2',
        2 => 'MiMo-v2.5-pro-Key2',
        3 => 'mimo2::mimov2.5pro',
        4 => 'mimo2::mimo-v2.5-pro',
        5 => 'xiaomi-mimo-v2.5-pro-key2',
      ),
    ),
    'lite' => 
    array (
      'enabled' => true,
      'zero_token' => true,
      'no_token_charge' => true,
      'is_free' => true,
      'free' => true,
      'api_token_multiplier' => 0,
      'label' => 'Spark Lite',
      'base_url' => 'https://spark-api-open.xf-yun.com/v1',
      'model_name' => 'lite',
      'resource_id' => '0',
      'auth_type' => 'api_password',
      'api_password' => '',
      'timeout' => 60,
      'temperature' => 0.6,
      'max_tokens' => 1200,
    ),
    'pro' => 
    array (
      'enabled' => true,
      'zero_token' => true,
      'no_token_charge' => true,
      'is_free' => true,
      'free' => true,
      'api_token_multiplier' => 0,
      'label' => '进阶 Pro 版',
      'type' => 'chat',
      'protocol' => 'maas_bearer_http',
      'base_url' => 'https://maas-api.cn-huabei-1.xf-yun.com/v2',
      'path' => '/chat/completions',
      'model_name' => 'xop35qwen2b',
      'resource_id' => '0',
      'auth_type' => 'bearer',
      'api_key' => '',
      'app_id' => '',
      'timeout' => 90,
      'temperature' => 0.5,
      'max_tokens' => 4096,
      'requires_quota' => false,
      'stream_supported' => true,
      'aliases' => 
      array (
        0 => 'pro',
        1 => 'qwen3.5-2b',
        2 => 'qwen35-2b',
        3 => 'advanced-pro',
      ),
    ),
    'reasoner' => 
    array (
      'enabled' => true,
      'zero_token' => true,
      'no_token_charge' => true,
      'is_free' => true,
      'free' => true,
      'api_token_multiplier' => 0,
      'label' => 'NVIDIA GPT-OSS-20B',
      'type' => 'reasoning',
      'protocol' => 'maas_bearer_http',
      'base_url' => 'https://integrate.api.nvidia.com/v1',
      'path' => '/chat/completions',
      'model_name' => 'openai/gpt-oss-20b',
      'resource_id' => '',
      'patch_id' => '',
      'auth_type' => 'bearer',
      'api_key' => '',
      'timeout' => 120,
      'temperature' => 1,
      'top_p' => 1,
      'presence_penalty' => 0,
      'frequency_penalty' => 0,
      'max_tokens' => 4096,
      'requires_quota' => true,
      'stream_supported' => true,
      'supports_thinking' => false,
      'aliases' => 
      array (
        0 => 'gpt-oss-20b',
        1 => 'nvidia-gpt-oss-20b',
        2 => 'openai-gpt-oss-20b',
      ),
    ),
    'nvidia-seed-oss-36b' => 
    array (
      'enabled' => true,
      'zero_token' => true,
      'no_token_charge' => true,
      'is_free' => true,
      'free' => true,
      'api_token_multiplier' => 0,
      'label' => 'NVIDIA Seed-OSS-36B',
      'type' => 'reasoning',
      'protocol' => 'maas_bearer_http',
      'base_url' => 'https://integrate.api.nvidia.com/v1',
      'path' => '/chat/completions',
      'model_name' => 'bytedance/seed-oss-36b-instruct',
      'resource_id' => '',
      'auth_type' => 'bearer',
      'api_key' => '',
      'timeout' => 120,
      'temperature' => 1.1,
      'top_p' => 0.95,
      'presence_penalty' => 0,
      'frequency_penalty' => 0,
      'max_tokens' => 4096,
      'stream_supported' => true,
      'extra_body' => 
      array (
        'thinking_budget' => -1,
      ),
      'aliases' => 
      array (
        0 => 'nvidia',
        1 => 'seed',
        2 => 'seed-oss',
        3 => 'bytedance-seed',
      ),
    ),
    'nvidia-minimax-m2-7' => 
    array (
      'enabled' => true,
      'zero_token' => true,
      'no_token_charge' => true,
      'is_free' => true,
      'free' => true,
      'api_token_multiplier' => 0,
      'label' => 'NVIDIA MiniMax-M2.7',
      'type' => 'reasoning',
      'protocol' => 'maas_bearer_http',
      'base_url' => 'https://integrate.api.nvidia.com/v1',
      'path' => '/chat/completions',
      'model_name' => 'minimaxai/minimax-m2.7',
      'resource_id' => '',
      'patch_id' => '',
      'auth_type' => 'bearer',
      'api_key' => '',
      'api_password' => '',
      'api_secret' => '',
      'app_id' => '',
      'timeout' => 180,
      'temperature' => 1,
      'max_tokens' => 16384,
      'top_p' => 0.95,
      'presence_penalty' => 0,
      'frequency_penalty' => 0,
      'requires_quota' => false,
      'stream_supported' => true,
      'supports_thinking' => true,
      'extra_body' => 
      array (
        'chat_template_kwargs' => 
        array (
          'enable_thinking' => true,
        ),
      ),
      'aliases' => 
      array (
        0 => 'minimax-m2.7',
        1 => 'minimax-m2-7',
        2 => 'minimaxai-minimax-m2.7',
        3 => 'nvidia-minimax-m2-7',
      ),
    ),
    'nvidia-qwen3-5-122b-a10b' => 
    array (
      'enabled' => true,
      'zero_token' => true,
      'no_token_charge' => true,
      'is_free' => true,
      'free' => true,
      'api_token_multiplier' => 0,
      'label' => 'NVIDIA Qwen3.5-122B-A10B',
      'type' => 'reasoning',
      'protocol' => 'maas_bearer_http',
      'base_url' => 'https://integrate.api.nvidia.com/v1',
      'path' => '/chat/completions',
      'model_name' => 'qwen/qwen3.5-122b-a10b',
      'resource_id' => '',
      'patch_id' => '',
      'auth_type' => 'bearer',
      'api_key' => '',
      'api_password' => '',
      'api_secret' => '',
      'app_id' => '',
      'timeout' => 180,
      'temperature' => 1,
      'max_tokens' => 16384,
      'top_p' => 0.95,
      'presence_penalty' => 0,
      'frequency_penalty' => 0,
      'requires_quota' => false,
      'stream_supported' => true,
      'supports_thinking' => true,
      'extra_body' => 
      array (
        'chat_template_kwargs' => 
        array (
          'enable_thinking' => true,
        ),
      ),
      'aliases' => 
      array (
        0 => 'qwen3.5-122b-a10b',
        1 => 'qwen-122b-a10b',
        2 => 'qwen35-122b-a10b',
        3 => 'nvidia-qwen3-5-122b-a10b',
      ),
    ),
    'nvidia-qwen3-5-397b-a17b' => 
    array (
      'enabled' => true,
      'zero_token' => true,
      'no_token_charge' => true,
      'is_free' => true,
      'free' => true,
      'api_token_multiplier' => 0,
      'label' => 'NVIDIA Qwen3.5-397B-A17B',
      'type' => 'reasoning',
      'protocol' => 'maas_bearer_http',
      'base_url' => 'https://integrate.api.nvidia.com/v1',
      'path' => '/chat/completions',
      'model_name' => 'qwen/qwen3.5-397b-a17b',
      'resource_id' => '',
      'patch_id' => '',
      'auth_type' => 'bearer',
      'api_key' => '',
      'api_password' => '',
      'api_secret' => '',
      'app_id' => '',
      'timeout' => 240,
      'temperature' => 1,
      'max_tokens' => 16384,
      'top_p' => 0.95,
      'presence_penalty' => 0,
      'frequency_penalty' => 0,
      'requires_quota' => false,
      'stream_supported' => true,
      'supports_thinking' => true,
      'supports_image_input' => true,
      'extra_body' => 
      array (
        'chat_template_kwargs' => 
        array (
          'enable_thinking' => true,
        ),
      ),
      'aliases' => 
      array (
        0 => 'qwen3.5-397b-a17b',
        1 => 'qwen-397b-a17b',
        2 => 'qwen35-397b-a17b',
        3 => 'nvidia-qwen3-5-397b-a17b',
      ),
    ),
    'nvidia-gemma-4-31b-it' => 
    array (
      'enabled' => true,
      'zero_token' => true,
      'no_token_charge' => true,
      'is_free' => true,
      'free' => true,
      'api_token_multiplier' => 0,
      'label' => 'NVIDIA Gemma-4-31B-IT',
      'type' => 'reasoning',
      'protocol' => 'maas_bearer_http',
      'base_url' => 'https://integrate.api.nvidia.com/v1',
      'path' => '/chat/completions',
      'model_name' => 'google/gemma-4-31b-it',
      'resource_id' => '',
      'patch_id' => '',
      'auth_type' => 'bearer',
      'api_key' => '',
      'api_password' => '',
      'api_secret' => '',
      'app_id' => '',
      'timeout' => 180,
      'temperature' => 1,
      'max_tokens' => 16384,
      'top_p' => 0.95,
      'presence_penalty' => 0,
      'frequency_penalty' => 0,
      'requires_quota' => false,
      'stream_supported' => true,
      'supports_thinking' => true,
      'extra_body' => 
      array (
        'chat_template_kwargs' => 
        array (
          'enable_thinking' => true,
        ),
      ),
      'aliases' => 
      array (
        0 => 'gemma-4-31b-it',
        1 => 'gemma-4',
        2 => 'google-gemma-4-31b',
      ),
    ),
    'nvidia-glm-5-1' => 
    array (
      'enabled' => false,
      'zero_token' => true,
      'no_token_charge' => true,
      'is_free' => true,
      'free' => true,
      'api_token_multiplier' => 0,
      'label' => 'NVIDIA Z-AI GLM-5.1',
      'type' => 'reasoning',
      'protocol' => 'maas_bearer_http',
      'base_url' => 'https://integrate.api.nvidia.com/v1',
      'path' => '/chat/completions',
      'model_name' => 'z-ai/glm-5.1',
      'resource_id' => '',
      'patch_id' => '',
      'auth_type' => 'bearer',
      'api_key' => '',
      'api_password' => '',
      'api_secret' => '',
      'app_id' => '',
      'timeout' => 180,
      'temperature' => 1,
      'max_tokens' => 16384,
      'top_p' => 1,
      'presence_penalty' => 0,
      'frequency_penalty' => 0,
      'requires_quota' => false,
      'stream_supported' => true,
      'supports_thinking' => true,
      'extra_body' => 
      array (
        'chat_template_kwargs' => 
        array (
          'enable_thinking' => true,
          'clear_thinking' => false,
        ),
      ),
      'aliases' => 
      array (
        0 => 'glm-5.1',
        1 => 'z-ai-glm-5.1',
        2 => 'nvidia-glm-5-1',
      ),
    ),
    'qwen-image-2512' => 
    array (
      'enabled' => true,
      'label' => 'Qwen-Image-2512',
      'base_url' => 'https://maas-api.cn-huabei-1.xf-yun.com',
      'path' => '/v2.1/tti',
      'model_name' => 'xopqwentti20b',
      'resource_id' => '0',
      'patch_id' => '0',
      'type' => 'image_generation',
      'protocol' => 'xfyun_signed_http',
      'auth_type' => 'signed',
      'app_id' => '',
      'api_key' => '',
      'api_secret' => '',
      'timeout' => 120,
      'image_width' => 1024,
      'image_height' => 1024,
      'image_steps' => 20,
      'image_guidance_scale' => 5.0,
      'image_scheduler' => 'Euler',
      'negative_prompt' => '',
    ),
    'qwen3-embedding-8b' => 
    array (
      'enabled' => true,
      'label' => 'Qwen3-Embedding-8B',
      'base_url' => 'https://maas-api.cn-huabei-1.xf-yun.com/v2',
      'path' => '/embeddings',
      'model_name' => 'Qwen3-Embedding-8B',
      'resource_id' => '0',
      'type' => 'embedding',
      'protocol' => 'maas_bearer_http',
      'auth_type' => 'bearer',
      'api_key' => '',
      'timeout' => 60,
      'encoding_format' => 'float',
      'embedding_dimensions' => 0,
    ),
    'z-image-turbo' => 
    array (
      'enabled' => true,
      'label' => 'Z-Image-Turbo',
      'type' => 'image_generation',
      'protocol' => 'xfyun_signed_http',
      'base_url' => 'https://maas-api.cn-huabei-1.xf-yun.com',
      'path' => '/v2.1/tti',
      'model_name' => 'xopzimageturbo',
      'resource_id' => '0',
      'patch_id' => '0',
      'auth_type' => 'signed',
      'app_id' => getenv('XFYUN_IMAGE_APP_ID') ?: '8e0a80e6',
      'api_key' => getenv('XFYUN_IMAGE_API_KEY') ?: '54aeff79437d35ab663e0d205068b0aa',
      'api_secret' => getenv('XFYUN_IMAGE_API_SECRET') ?: 'MDQ2NmQwOWIzMWEyZWMwNjkzMGZlYzAy',
      'timeout' => 120,
      'image_width' => 1024,
      'image_height' => 1024,
      'image_steps' => 20,
      'image_guidance_scale' => 5.0,
      'image_scheduler' => 'Euler',
      'negative_prompt' => '',
      'stream_supported' => false,
      'aliases' => 
      array (
        0 => 'z-image',
        1 => 'z-image-turbo',
        2 => 'xopzimageturbo',
      ),
    ),
    'zhipu-glm-5-1' => 
    array (
      'enabled' => false,
      'label' => '智谱 GLM-4.7',
      'type' => 'chat',
      'provider' => 'zhipu',
      'protocol' => 'openai_compatible',
      'base_url' => 'https://open.bigmodel.cn/api/paas/v4',
      'path' => '/chat/completions',
      'model_name' => 'glm-4.7',
      'resource_id' => '',
      'patch_id' => '',
      'auth_type' => 'bearer',
      'api_key' => getenv('ZHIPU_API_KEY') ?: 'ff8ad59703df4ac694aee83300acc58c.nwmBTS72mC0UrDi7',
      'api_password' => '',
      'api_secret' => '',
      'app_id' => 'ff8a...c58c',
      'timeout' => 120,
      'temperature' => 1.0,
      'max_tokens' => 4096,
      'top_p' => 0.9,
      'requires_quota' => false,
      'stream_supported' => true,
      'supports_thinking' => true,
      'aliases' => 
      array (
        0 => 'glm-4.7',
        1 => 'glm-5',
        2 => 'zhipu',
        3 => 'bigmodel',
        4 => 'zhipu-language',
      ),
    ),
  ),
);
