<?php
declare(strict_types=1);
require_once __DIR__ . '/_common.php';
admin_require_csrf();
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    try {
        $action=(string)($_POST['action']??'');
        if($action==='save_notice'){
            $rows=admin_announcements(); $id=admin_int($_POST['id']??0); $row=['id'=>$id>0?$id:next_id($rows),'title'=>trim((string)($_POST['title']??'')),'content'=>trim((string)($_POST['content']??'')),'type'=>(string)($_POST['type']??'info'),'enabled'=>!empty($_POST['enabled']),'updated_at'=>admin_now(),'created_at'=>admin_now()]; if($row['title']===''||$row['content']==='') throw new RuntimeException('标题和内容不能为空。'); $found=false; foreach($rows as &$r){ if((int)($r['id']??0)===$id){$row['created_at']=$r['created_at']??admin_now();$r=$row;$found=true;break;}} unset($r); if(!$found)$rows[]=$row; admin_save_announcements($rows); admin_flash('ok','公告已保存。');
        } elseif($action==='delete_notice'){ $id=admin_int($_POST['id']??0); $rows=array_values(array_filter(admin_announcements(),fn($r)=>(int)($r['id']??0)!==$id)); admin_save_announcements($rows); admin_flash('ok','公告已删除。');
        } elseif($action==='broadcast'){ $title=trim((string)($_POST['title']??'站内通知')); $content=trim((string)($_POST['content']??'')); if($content==='') throw new RuntimeException('通知内容不能为空。'); foreach(users_all() as $u){ create_notification((int)($u['id']??0),$title,$content,'admin','account.html'); } admin_flash('ok','已向全部用户广播通知。'); }
    } catch(Throwable $e){ admin_flash('error',$e->getMessage()); }
    admin_redirect('/admin/content.php');
}
$notices=admin_announcements(); usort($notices,fn($a,$b)=>strcmp((string)($b['updated_at']??''),(string)($a['updated_at']??''))); $editId=admin_int($_GET['edit']??0); $edit=null; foreach($notices as $n){ if((int)($n['id']??0)===$editId){$edit=$n;break;}}
admin_render_header('内容公告','管理站点公告，并可向所有用户广播站内通知。');
admin_cards([['公告数',count($notices),'config/announcements.json'],['启用公告',count(array_filter($notices,fn($n)=>!empty($n['enabled']))),'前台可读取'],['用户通知',count(read_store(NOTIFICATIONS_FILE)),'现有通知总数'],['用户数',count(users_all()),'可广播']]);
$form=$edit?:['id'=>0,'title'=>'','content'=>'','type'=>'info','enabled'=>true];
?>
<section class="split"><div class="panel"><h2><?= $edit?'编辑公告':'新增公告' ?></h2><form class="form" method="post"><input type="hidden" name="csrf" value="<?= h(admin_csrf_token()) ?>"><input type="hidden" name="action" value="save_notice"><input type="hidden" name="id" value="<?= h($form['id']??0) ?>"><label>标题<input name="title" value="<?= h($form['title']??'') ?>" required></label><label>类型<select name="type"><option value="info" <?= (($form['type']??'')==='info')?'selected':'' ?>>info</option><option value="success" <?= (($form['type']??'')==='success')?'selected':'' ?>>success</option><option value="warning" <?= (($form['type']??'')==='warning')?'selected':'' ?>>warning</option></select></label><label>内容<textarea name="content" required><?= h($form['content']??'') ?></textarea></label><label><input type="checkbox" name="enabled" value="1" <?= !empty($form['enabled'])?'checked':'' ?>> 启用公告</label><div class="actions"><button class="btn green">保存公告</button><a class="btn secondary" href="/admin/content.php">清空</a></div></form></div><div class="panel"><h2>全站广播</h2><form class="form" method="post"><input type="hidden" name="csrf" value="<?= h(admin_csrf_token()) ?>"><input type="hidden" name="action" value="broadcast"><label>标题<input name="title" value="站内通知"></label><label>内容<textarea name="content" required></textarea></label><button class="btn blue" data-confirm="确认向全部用户发送通知？">发送广播</button></form></div></section>
<div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>标题</th><th>内容</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody><?php foreach($notices as $n): ?><tr><td><?= h($n['id']??'') ?></td><td><?= h($n['title']??'') ?></td><td><?= h(mb_substr((string)($n['content']??''),0,120,'UTF-8')) ?></td><td><span class="badge <?= !empty($n['enabled'])?'green':'red' ?>"><?= !empty($n['enabled'])?'启用':'停用' ?></span></td><td><?= h($n['updated_at']??'') ?></td><td><div class="actions"><a class="btn secondary" href="/admin/content.php?edit=<?= h($n['id']??0) ?>">编辑</a><form method="post"><input type="hidden" name="csrf" value="<?= h(admin_csrf_token()) ?>"><input type="hidden" name="action" value="delete_notice"><input type="hidden" name="id" value="<?= h($n['id']??0) ?>"><button class="btn red" data-confirm="确认删除公告？">删除</button></form></div></td></tr><?php endforeach; if(!$notices): ?><tr><td colspan="6" class="muted">暂无公告</td></tr><?php endif; ?></tbody></table></div>
<?php admin_render_footer(); ?>
