<?php
declare(strict_types=1);
require_once __DIR__ . '/_common.php';
admin_require_csrf();
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    try {
        if (!function_exists('ai_api_packages')) throw new RuntimeException('AI API 套餐模块不可用。');
        $action=(string)($_POST['action']??''); $packages=ai_api_packages(true);
        if ($action==='save') {
            $id=preg_replace('/[^a-zA-Z0-9_-]/','',(string)($_POST['id']??'')); if($id==='') throw new RuntimeException('套餐 ID 不能为空。');
            $found=false; foreach($packages as &$p){ if(($p['id']??'')===$id){ $found=true; $p=array_merge($p,[ 'title'=>(string)($_POST['title']??$id),'description'=>(string)($_POST['description']??''),'tokens'=>admin_int($_POST['tokens']??0),'price'=>(float)($_POST['price']??0),'currency'=>(string)($_POST['currency']??'CNY'),'kind'=>(string)($_POST['kind']??'topup'),'period_days'=>admin_int($_POST['period_days']??0),'badge'=>(string)($_POST['badge']??''),'recommended'=>!empty($_POST['recommended']),'enabled'=>!empty($_POST['enabled']),'auto_grant'=>!empty($_POST['auto_grant']),'once_per_user'=>!empty($_POST['once_per_user']),'features'=>array_values(array_filter(array_map('trim',preg_split('/\r?\n/',(string)($_POST['features']??''))?:[]))),'sort_order'=>admin_int($_POST['sort_order']??99)]); break; }} unset($p);
            if(!$found){ $packages[]=[ 'id'=>$id,'title'=>(string)($_POST['title']??$id),'description'=>(string)($_POST['description']??''),'tokens'=>admin_int($_POST['tokens']??0),'price'=>(float)($_POST['price']??0),'currency'=>(string)($_POST['currency']??'CNY'),'kind'=>(string)($_POST['kind']??'topup'),'period_days'=>admin_int($_POST['period_days']??0),'badge'=>(string)($_POST['badge']??''),'recommended'=>!empty($_POST['recommended']),'enabled'=>!empty($_POST['enabled']),'auto_grant'=>!empty($_POST['auto_grant']),'once_per_user'=>!empty($_POST['once_per_user']),'features'=>array_values(array_filter(array_map('trim',preg_split('/\r?\n/',(string)($_POST['features']??''))?:[]))),'sort_order'=>admin_int($_POST['sort_order']??99) ]; }
            ai_api_save_packages($packages); admin_flash('ok','套餐已保存。');
        } elseif ($action==='delete') { $id=(string)($_POST['id']??''); $packages=array_values(array_filter($packages,fn($p)=>($p['id']??'')!==$id)); ai_api_save_packages($packages); admin_flash('ok','套餐已删除。'); }
    } catch(Throwable $e){ admin_flash('error',$e->getMessage()); }
    admin_redirect('/admin/packages.php');
}
$packages=function_exists('ai_api_packages')?ai_api_packages(true):[]; $editId=(string)($_GET['edit']??''); $edit=null; foreach($packages as $p){ if(($p['id']??'')===$editId){$edit=$p;break;}}
admin_render_header('套餐管理','管理试用包、月卡、加量包、自动发放和展示角标。');
admin_cards([['套餐总数',count($packages),'含下架'],['已启用',count(array_filter($packages,fn($p)=>!empty($p['enabled']))),'前台可见'],['自动发放',count(array_filter($packages,fn($p)=>!empty($p['auto_grant']))),'免费/试用'],['推荐',count(array_filter($packages,fn($p)=>!empty($p['recommended']))),'首页高亮']]);
$blank=['id'=>'','title'=>'','description'=>'','tokens'=>0,'price'=>0,'currency'=>'CNY','kind'=>'topup','period_days'=>0,'badge'=>'','recommended'=>false,'enabled'=>true,'auto_grant'=>false,'once_per_user'=>false,'features'=>[],'sort_order'=>99]; $form=$edit?:$blank;
?>
<section class="panel"><h2><?= $edit ? '编辑套餐' : '新增套餐' ?></h2><form class="form grid3" method="post"><input type="hidden" name="csrf" value="<?= h(admin_csrf_token()) ?>"><input type="hidden" name="action" value="save"><label>ID<input name="id" value="<?= h($form['id']) ?>" <?= $edit?'readonly':'' ?> required></label><label>标题<input name="title" value="<?= h($form['title']) ?>" required></label><label>角标<input name="badge" value="<?= h($form['badge']) ?>"></label><label>Token<input name="tokens" type="number" value="<?= h($form['tokens']) ?>"></label><label>价格<input name="price" type="number" step="0.01" value="<?= h($form['price']) ?>"></label><label>币种<input name="currency" value="<?= h($form['currency']) ?>"></label><label>类型<select name="kind"><option value="trial" <?= ($form['kind']==='trial')?'selected':'' ?>>trial</option><option value="subscription" <?= ($form['kind']==='subscription')?'selected':'' ?>>subscription</option><option value="topup" <?= ($form['kind']==='topup')?'selected':'' ?>>topup</option></select></label><label>周期天数<input name="period_days" type="number" value="<?= h($form['period_days']) ?>"></label><label>排序<input name="sort_order" type="number" value="<?= h($form['sort_order']) ?>"></label><label style="grid-column:1/-1">描述<textarea name="description"><?= h($form['description']) ?></textarea></label><label style="grid-column:1/-1">特性（每行一条）<textarea name="features"><?= h(implode("\n", (array)$form['features'])) ?></textarea></label><label><input type="checkbox" name="enabled" value="1" <?= !empty($form['enabled'])?'checked':'' ?>> 启用</label><label><input type="checkbox" name="recommended" value="1" <?= !empty($form['recommended'])?'checked':'' ?>> 推荐</label><label><input type="checkbox" name="auto_grant" value="1" <?= !empty($form['auto_grant'])?'checked':'' ?>> 自动发放</label><label><input type="checkbox" name="once_per_user" value="1" <?= !empty($form['once_per_user'])?'checked':'' ?>> 每人一次</label><div class="actions" style="grid-column:1/-1"><button class="btn green">保存套餐</button><a class="btn secondary" href="/admin/packages.php">清空表单</a></div></form></section>
<div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>标题</th><th>Token/价格</th><th>类型</th><th>状态</th><th>特性</th><th>操作</th></tr></thead><tbody><?php foreach($packages as $p): ?><tr><td><code><?= h($p['id']??'') ?></code></td><td><strong><?= h($p['title']??'') ?></strong><br><span class="muted"><?= h($p['description']??'') ?></span></td><td><?= h($p['tokens']??0) ?> Token<br><span class="muted"><?= h($p['price']??0) ?> <?= h($p['currency']??'CNY') ?></span></td><td><?= h($p['kind']??'') ?><br><span class="muted"><?= h($p['period_days']??0) ?> 天</span></td><td><span class="badge <?= !empty($p['enabled'])?'green':'red' ?>"><?= !empty($p['enabled'])?'启用':'停用' ?></span> <?= !empty($p['recommended'])?'<span class="badge amber">推荐</span>':'' ?></td><td><?= h(implode(' / ',array_slice((array)($p['features']??[]),0,3))) ?></td><td><div class="actions"><a class="btn secondary" href="/admin/packages.php?edit=<?= h($p['id']??'') ?>">编辑</a><form method="post"><input type="hidden" name="csrf" value="<?= h(admin_csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= h($p['id']??'') ?>"><button class="btn red" data-confirm="确认删除套餐？">删除</button></form></div></td></tr><?php endforeach; if(!$packages): ?><tr><td colspan="7" class="muted">暂无套餐</td></tr><?php endif; ?></tbody></table></div>
<?php admin_render_footer(); ?>
